export const styles = {
  container: {
    display: "flex",
    height: "100vh",
    backgroundColor: "#0f1419",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif',
    color: "#ffffff",
  },
  sidebar: {
    width: "280px",
    backgroundColor: "#0a0f14",
    borderRight: "1px solid rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "column",
  },
  sidebarHeader: {
    padding: "20px 16px 16px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
    background:
      "linear-gradient(135deg, rgba(245, 158, 11, 0.1) 0%, rgba(251, 191, 36, 0.05) 100%)",
  },
  logoSection: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "16px",
  },
  logo: {
    fontSize: "20px",
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  settingsButton: {
    padding: "6px",
    backgroundColor: "transparent",
    border: "none",
    color: "#a0aec0",
    cursor: "pointer",
    borderRadius: "6px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s",
  },
  tokenBar: {
    height: "4px",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "2px",
    overflow: "hidden",
  },
  tokenProgress: {
    height: "100%",
    background: "linear-gradient(90deg, #f59e0b 0%, #fbbf24 100%)",
    borderRadius: "2px",
    transition: "width 0.3s ease",
    boxShadow: "0 0 10px rgba(245, 158, 11, 0.3)",
  },
  newChatButton: {
    width: "100%",
    padding: "12px",
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    color: "#0f172a",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    marginTop: "12px",
    transition: "all 0.2s",
    boxShadow: "0 4px 12px rgba(245, 158, 11, 0.3)",
  },
  searchContainer: {
    padding: "12px 16px",
    position: "relative",
    width: "100%",
    boxSizing: "border-box",
  },
  searchInput: {
    width: "calc(100% - 0px)",
    padding: "8px 12px 8px 36px",
    backgroundColor: "#151b26",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "8px",
    color: "#ffffff",
    fontSize: "14px",
    outline: "none",
    boxSizing: "border-box",
  },
  searchIcon: {
    position: "absolute",
    left: "28px",
    top: "50%",
    transform: "translateY(-50%)",
    color: "#6b7280",
    pointerEvents: "none",
  },
  chatList: {
    flex: 1,
    overflowY: "auto",
    padding: "8px",
  },
  chatItem: {
    padding: "10px 12px",
    borderRadius: "8px",
    cursor: "pointer",
    marginBottom: "4px",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    transition: "all 0.2s",
  },
  chatItemActive: {
    background:
      "linear-gradient(135deg, rgba(245, 158, 11, 0.15) 0%, rgba(251, 191, 36, 0.1) 100%)",
    border: "1px solid rgba(245, 158, 11, 0.3)",
    boxShadow: "0 2px 8px rgba(245, 158, 11, 0.2)",
  },
  chatInfo: {
    flex: 1,
    minWidth: 0,
  },
  chatTitle: {
    fontSize: "14px",
    fontWeight: "500",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
  },
  chatPreview: {
    fontSize: "12px",
    color: "#6b7280",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chatMenu: {
    position: "absolute",
    right: "8px",
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 10,
  },
  menuButton: {
    padding: "4px",
    backgroundColor: "transparent",
    border: "none",
    color: "#6b7280",
    cursor: "pointer",
    borderRadius: "4px",
    opacity: 0,
    transition: "opacity 0.2s",
  },
  menuDropdown: {
    position: "absolute",
    right: "0",
    top: "100%",
    marginTop: "4px",
    backgroundColor: "#151b26",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "8px",
    padding: "4px",
    minWidth: "120px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.3)",
  },
  menuItem: {
    padding: "8px 12px",
    fontSize: "13px",
    color: "#ffffff",
    cursor: "pointer",
    borderRadius: "6px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "background-color 0.2s",
  },
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#0f1419",
  },
  chatHeader: {
    padding: "16px 20px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background:
      "linear-gradient(135deg, rgba(30, 41, 59, 0.8) 0%, rgba(51, 65, 85, 0.6) 100%)",
    backdropFilter: "blur(10px)",
  },
  chatHeaderInfo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  modelSelector: {
    padding: "6px 12px",
    backgroundColor: "#151b26",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "6px",
    color: "#ffffff",
    fontSize: "13px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  chatArea: {
    flex: 1,
    overflowY: "auto",
    padding: "20px",
  },
  messageGroup: {
    marginBottom: "24px",
  },
  message: {
    display: "flex",
    gap: "12px",
    marginBottom: "16px",
  },
  messageAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    backgroundColor: "#151b26",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  messageContent: {
    flex: 1,
  },
  messageHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "4px",
  },
  messageName: {
    fontSize: "14px",
    fontWeight: "600",
  },
  messageTime: {
    fontSize: "12px",
    color: "#6b7280",
  },
  messageText: {
    fontSize: "14px",
    lineHeight: "1.6",
    color: "#e5e7eb",
  },
  messageActions: {
    display: "flex",
    gap: "4px",
    marginTop: "8px",
    transition: "opacity 0.2s ease",
  },
  actionButton: {
    padding: "4px 8px",
    backgroundColor: "transparent",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "6px",
    color: "#6b7280",
    fontSize: "12px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    transition: "all 0.2s",
  },
  typingIndicator: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    backgroundColor: "#151b26",
    borderRadius: "16px",
    width: "fit-content",
  },
  typingDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    animation: "pulse 1.4s infinite",
  },
  inputContainer: {
    padding: "16px 20px",
    borderTop: "1px solid rgba(255, 255, 255, 0.1)",
  },
  inputWrapper: {
    display: "flex",
    alignItems: "flex-end",
    gap: "12px",
    backgroundColor: "#151b26",
    borderRadius: "12px",
    padding: "12px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  textInput: {
    flex: 1,
    backgroundColor: "transparent",
    border: "none",
    color: "#ffffff",
    fontSize: "14px",
    outline: "none",
    resize: "none",
    minHeight: "20px",
    maxHeight: "120px",
  },
  sendButton: {
    padding: "10px 16px",
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    border: "none",
    borderRadius: "8px",
    color: "#0f172a",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    transition: "all 0.2s",
    boxShadow: "0 4px 12px rgba(245, 158, 11, 0.3)",
  },
  tokenWarning: {
    padding: "8px 12px",
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    border: "1px solid rgba(239, 68, 68, 0.3)",
    borderRadius: "6px",
    marginBottom: "8px",
    fontSize: "13px",
    color: "#fbbf24",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  scrollToBottomButton: {
    position: "absolute",
    bottom: "20px",
    right: "20px",
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#151b26",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    color: "#ffffff",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.3)",
    transition: "all 0.2s",
  },
  stopButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 16px",
    backgroundColor: "#ef4444",
    color: "white",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
    width: "100%",
    justifyContent: "center",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    backgroundColor: "#0f1419",
    borderRadius: "12px",
    padding: "24px",
    maxWidth: "420px",
    width: "90%",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    boxShadow: "0 10px 40px rgba(0, 0, 0, 0.5)",
  },
  modalTitle: {
    fontSize: "20px",
    fontWeight: "600",
    marginBottom: "12px",
    color: "#ffffff",
  },
  modalBody: {
    fontSize: "14px",
    color: "#a0aec0",
    marginBottom: "20px",
    lineHeight: "1.6",
  },
  modalButtons: {
    display: "flex",
    gap: "12px",
    justifyContent: "flex-end",
  },
  modalButton: {
    padding: "8px 16px",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s",
    border: "none",
  },
  modalPrimaryButton: {
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    color: "#0f172a",
    boxShadow: "0 4px 12px rgba(245, 158, 11, 0.3)",
  },
  modalSecondaryButton: {
    backgroundColor: "#151b26",
    color: "#ffffff",
    border: "1px solid rgba(255, 255, 255, 0.2)",
  },
  settingsPanel: {
    position: "fixed",
    top: 0,
    right: 0,
    width: "400px",
    height: "100vh",
    background: "linear-gradient(180deg, #0a0f14 0%, #0f1419 100%)",
    borderLeft: "1px solid rgba(255, 255, 255, 0.1)",
    overflowY: "auto",
    transition: "transform 0.3s ease",
    zIndex: 999,
    boxShadow: "-4px 0 20px rgba(0, 0, 0, 0.3)",
  },
  settingsHeader: {
    padding: "20px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background:
      "linear-gradient(135deg, rgba(245, 158, 11, 0.1) 0%, rgba(251, 191, 36, 0.05) 100%)",
  },
  settingsTitle: {
    fontSize: "20px",
    fontWeight: "600",
    color: "#ffffff",
  },
  settingsSection: {
    padding: "20px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
  },
  sectionTitle: {
    fontSize: "16px",
    fontWeight: "600",
    marginBottom: "16px",
    color: "#ffffff",
  },
  settingsItem: {
    marginBottom: "16px",
  },
  settingsLabel: {
    fontSize: "13px",
    color: "#a0aec0",
    marginBottom: "6px",
  },
  settingsValue: {
    fontSize: "14px",
    color: "#ffffff",
  },
  usageBar: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "8px",
  },
  resetTimer: {
    fontSize: "12px",
    color: "#6b7280",
  },
  walletCard: {
    backgroundColor: "#151b26",
    borderRadius: "8px",
    padding: "16px",
    marginBottom: "16px",
  },
  walletBalance: {
    fontSize: "24px",
    fontWeight: "700",
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    marginBottom: "8px",
  },
  topUpButton: {
    width: "100%",
    padding: "12px",
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    color: "#0f172a",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s",
    boxShadow: "0 4px 12px rgba(245, 158, 11, 0.3)",
  },
  cardItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px",
    backgroundColor: "#151b26",
    borderRadius: "8px",
    marginBottom: "8px",
  },
  cardInfo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  toggleSwitch: {
    width: "44px",
    height: "24px",
    backgroundColor: "#1a1f2a",
    borderRadius: "12px",
    position: "relative",
    cursor: "pointer",
    transition: "background-color 0.3s",
  },
  toggleSlider: {
    position: "absolute",
    top: "2px",
    left: "2px",
    width: "20px",
    height: "20px",
    backgroundColor: "#ffffff",
    borderRadius: "50%",
    transition: "transform 0.3s",
  },
  toggleActive: {
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
  },
  transactionItem: {
    display: "flex",
    justifyContent: "space-between",
    padding: "8px 0",
    borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
  },
  titleInput: {
    backgroundColor: "transparent",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    borderRadius: "6px",
    padding: "4px 8px",
    color: "#ffffff",
    fontSize: "18px",
    fontWeight: "600",
    outline: "none",
  },
  emptyStateSidebar: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "60px 20px",
    height: "200px",
    textAlign: "center",
    color: "#6b7280",
    fontSize: "14px",
    lineHeight: "1.5",
  },
  buyButton: {
    padding: "8px 16px",
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    color: "#0f172a",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s",
    width: "auto",
    boxShadow: "0 2px 8px rgba(245, 158, 11, 0.3)",
  },
};
