export const styles = {
  container: {
    display: "flex",
    height: "100vh",
    backgroundColor: "#0f1419",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif',
    color: "#ffffff",
    position: "relative",
  },
  containerMobile: {
    flexDirection: "column",
  },
  sidebar: {
    width: "280px",
    backgroundColor: "#0a0f14",
    borderRight: "1px solid rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "column",
  },
  sidebarMobile: {
    position: "fixed",
    top: 0,
    left: 0,
    height: "100vh",
    width: "100vw",
    zIndex: 1000,
    transform: "translateX(-100%)",
    transition: "transform 0.3s ease",
    borderRight: "none",
  },
  sidebarMobileOpen: {
    transform: "translateX(0)",
  },
  sidebarOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 999,
    display: "none",
  },
  sidebarOverlayVisible: {
    display: "block",
  },
  sidebarHeader: {
    padding: "20px 16px 16px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
    background:
      "linear-gradient(135deg, rgba(245, 158, 11, 0.1) 0%, rgba(251, 191, 36, 0.05) 100%)",
  },
  sidebarHeaderMobile: {
    padding: "16px 12px 12px",
  },
  logoSection: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "16px",
  },
  logoSectionMobile: {
    marginBottom: "12px",
  },
  logo: {
    fontSize: "20px",
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  logoMobile: {
    fontSize: "18px",
  },
  settingsButton: {
    padding: "6px",
    backgroundColor: "transparent",
    border: "none",
    color: "#a0aec0",
    cursor: "pointer",
    borderRadius: "6px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s",
  },
  settingsButtonMobile: {
    padding: "8px",
    minWidth: "44px",
    minHeight: "44px",
  },
  mobileMenuButton: {
    display: "none",
    padding: "8px",
    backgroundColor: "transparent",
    border: "none",
    color: "#ffffff",
    cursor: "pointer",
    borderRadius: "6px",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "44px",
    minHeight: "44px",
  },
  mobileMenuButtonVisible: {
    display: "flex",
  },
  mobileCloseButton: {
    display: "none",
    position: "absolute",
    top: "16px",
    right: "16px",
    padding: "8px",
    backgroundColor: "transparent",
    border: "none",
    color: "#ffffff",
    cursor: "pointer",
    borderRadius: "6px",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "44px",
    minHeight: "44px",
    zIndex: 1001,
  },
  mobileCloseButtonVisible: {
    display: "flex",
  },
  tokenBar: {
    height: "4px",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "2px",
    overflow: "hidden",
  },
  tokenProgress: {
    height: "100%",
    background: "linear-gradient(90deg, #f59e0b 0%, #fbbf24 100%)",
    borderRadius: "2px",
    transition: "width 0.3s ease",
    boxShadow: "0 0 10px rgba(245, 158, 11, 0.3)",
  },
  newChatButton: {
    width: "100%",
    padding: "12px",
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    color: "#0f172a",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    marginTop: "12px",
    transition: "all 0.2s",
    boxShadow: "0 4px 12px rgba(245, 158, 11, 0.3)",
  },
  newChatButtonMobile: {
    padding: "14px",
    fontSize: "16px",
    minHeight: "48px",
  },
  searchContainer: {
    padding: "12px 16px",
    position: "relative",
    width: "100%",
    boxSizing: "border-box",
  },
  searchContainerMobile: {
    padding: "8px 12px",
  },
  searchInput: {
    width: "calc(100% - 0px)",
    padding: "8px 12px 8px 36px",
    backgroundColor: "#151b26",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "8px",
    color: "#ffffff",
    fontSize: "14px",
    outline: "none",
    boxSizing: "border-box",
  },
  searchInputMobile: {
    padding: "12px 12px 12px 40px",
    fontSize: "16px", // Prevent zoom on iOS
    minHeight: "44px",
  },
  searchIcon: {
    position: "absolute",
    left: "28px",
    top: "50%",
    transform: "translateY(-50%)",
    color: "#6b7280",
    pointerEvents: "none",
  },
  searchIconMobile: {
    left: "24px",
  },
  chatList: {
    flex: 1,
    overflowY: "auto",
    padding: "8px",
  },
  chatListMobile: {
    padding: "4px",
  },
  chatItem: {
    padding: "10px 12px",
    borderRadius: "8px",
    cursor: "pointer",
    marginBottom: "4px",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    transition: "all 0.2s",
  },
  chatItemMobile: {
    padding: "14px 12px",
    marginBottom: "6px",
    minHeight: "48px",
  },
  chatItemActive: {
    background:
      "linear-gradient(135deg, rgba(245, 158, 11, 0.15) 0%, rgba(251, 191, 36, 0.1) 100%)",
    border: "1px solid rgba(245, 158, 11, 0.3)",
    boxShadow: "0 2px 8px rgba(245, 158, 11, 0.2)",
  },
  chatInfo: {
    flex: 1,
    minWidth: 0,
  },
  chatTitle: {
    fontSize: "14px",
    fontWeight: "500",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
  },
  chatTitleMobile: {
    fontSize: "16px",
  },
  chatPreview: {
    fontSize: "12px",
    color: "#6b7280",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chatPreviewMobile: {
    fontSize: "14px",
  },
  chatMenu: {
    position: "absolute",
    right: "8px",
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 10,
  },
  menuButton: {
    padding: "4px",
    backgroundColor: "transparent",
    border: "none",
    color: "#6b7280",
    cursor: "pointer",
    borderRadius: "4px",
    opacity: 0,
    transition: "opacity 0.2s",
  },
  menuButtonMobile: {
    opacity: 1,
    padding: "8px",
    minWidth: "36px",
    minHeight: "36px",
  },
  menuDropdown: {
    position: "absolute",
    right: "0",
    top: "100%",
    marginTop: "4px",
    backgroundColor: "#151b26",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "8px",
    padding: "4px",
    minWidth: "120px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.3)",
  },
  menuDropdownMobile: {
    minWidth: "140px",
    padding: "6px",
  },
  menuItem: {
    padding: "8px 12px",
    fontSize: "13px",
    color: "#ffffff",
    cursor: "pointer",
    borderRadius: "6px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "background-color 0.2s",
  },
  menuItemMobile: {
    padding: "12px 16px",
    fontSize: "16px",
    minHeight: "44px",
  },
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#0f1419",
  },
  mainContentMobile: {
    width: "100%",
    height: "100vh",
  },
  chatHeader: {
    padding: "16px 20px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background:
      "linear-gradient(135deg, rgba(30, 41, 59, 0.8) 0%, rgba(51, 65, 85, 0.6) 100%)",
    backdropFilter: "blur(10px)",
  },
  chatHeaderMobile: {
    padding: "12px 16px",
    minHeight: "60px",
  },
  chatHeaderInfo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  chatHeaderInfoMobile: {
    gap: "8px",
    flex: 1,
  },
  modelSelector: {
    padding: "6px 12px",
    backgroundColor: "#151b26",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "6px",
    color: "#ffffff",
    fontSize: "13px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  modelSelectorMobile: {
    padding: "8px 12px",
    fontSize: "14px",
    minHeight: "40px",
  },
  chatArea: {
    flex: 1,
    overflowY: "auto",
    padding: "20px",
  },
  chatAreaMobile: {
    padding: "12px",
    paddingBottom: "20px",
  },
  messageGroup: {
    marginBottom: "24px",
  },
  messageGroupMobile: {
    marginBottom: "16px",
  },
  message: {
    display: "flex",
    gap: "12px",
    marginBottom: "16px",
  },
  messageMobile: {
    gap: "8px",
    marginBottom: "12px",
  },
  messageAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    backgroundColor: "#151b26",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  messageAvatarMobile: {
    width: "28px",
    height: "28px",
  },
  messageContent: {
    flex: 1,
  },
  messageContentMobile: {
    minWidth: 0, // Allow text to wrap properly
  },
  messageHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "4px",
  },
  messageHeaderMobile: {
    gap: "6px",
    flexWrap: "wrap",
  },
  messageName: {
    fontSize: "14px",
    fontWeight: "600",
  },
  messageNameMobile: {
    fontSize: "15px",
  },
  messageTime: {
    fontSize: "12px",
    color: "#6b7280",
  },
  messageTimeMobile: {
    fontSize: "13px",
  },
  messageText: {
    fontSize: "14px",
    lineHeight: "1.6",
    color: "#e5e7eb",
  },
  messageTextMobile: {
    fontSize: "15px",
    lineHeight: "1.5",
    wordBreak: "break-word", // Prevent long words from overflowing
  },
  messageActions: {
    display: "flex",
    gap: "4px",
    marginTop: "8px",
    transition: "opacity 0.2s ease",
  },
  messageActionsMobile: {
    gap: "6px",
    marginTop: "12px",
    flexWrap: "wrap",
  },
  actionButton: {
    padding: "4px 8px",
    backgroundColor: "transparent",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "6px",
    color: "#6b7280",
    fontSize: "12px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    transition: "all 0.2s",
  },
  actionButtonMobile: {
    padding: "8px 12px",
    fontSize: "14px",
    minHeight: "36px",
  },
  typingIndicator: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    backgroundColor: "#151b26",
    borderRadius: "16px",
    width: "fit-content",
  },
  typingIndicatorMobile: {
    padding: "10px 14px",
  },
  typingDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    animation: "pulse 1.4s infinite",
  },
  inputContainer: {
    padding: "16px 20px",
    borderTop: "1px solid rgba(255, 255, 255, 0.1)",
  },
  inputContainerMobile: {
    padding: "12px 16px",
    paddingBottom: "max(12px, env(safe-area-inset-bottom))", // Handle iPhone notch
  },
  inputWrapper: {
    display: "flex",
    alignItems: "flex-end",
    gap: "12px",
    backgroundColor: "#151b26",
    borderRadius: "12px",
    padding: "12px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  inputWrapperMobile: {
    gap: "8px",
    padding: "10px",
    borderRadius: "16px",
  },
  textInput: {
    flex: 1,
    backgroundColor: "transparent",
    border: "none",
    color: "#ffffff",
    fontSize: "14px",
    outline: "none",
    resize: "none",
    minHeight: "20px",
    maxHeight: "120px",
  },
  textInputMobile: {
    fontSize: "16px", // Prevent zoom on iOS
    minHeight: "24px",
    maxHeight: "100px",
  },
  sendButton: {
    padding: "10px 16px",
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    border: "none",
    borderRadius: "8px",
    color: "#0f172a",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    transition: "all 0.2s",
    boxShadow: "0 4px 12px rgba(245, 158, 11, 0.3)",
  },
  sendButtonMobile: {
    padding: "12px 16px",
    fontSize: "16px",
    minWidth: "48px",
    minHeight: "48px",
    borderRadius: "12px",
  },
  tokenWarning: {
    padding: "8px 12px",
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    border: "1px solid rgba(239, 68, 68, 0.3)",
    borderRadius: "6px",
    marginBottom: "8px",
    fontSize: "13px",
    color: "#fbbf24",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  tokenWarningMobile: {
    padding: "10px 14px",
    fontSize: "14px",
    marginBottom: "10px",
    borderRadius: "8px",
  },
  scrollToBottomButton: {
    position: "absolute",
    bottom: "20px",
    right: "20px",
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#101a22",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "#ffffff",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s",
    zIndex: 10,
  },
  scrollToBottomButtonMobile: {
    bottom: "100px", // Above mobile input area
    right: "16px",
    width: "48px",
    height: "48px",
  },
  stopButton: {
    padding: "8px 12px",
    backgroundColor: "#ef4444",
    border: "none",
    borderRadius: "6px",
    color: "#ffffff",
    fontSize: "12px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    transition: "all 0.2s",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
    padding: "20px",
    boxSizing: "border-box",
  },
  modalOverlayMobile: {
    padding: "16px",
  },
  modal: {
    backgroundColor: "#151b26",
    borderRadius: "12px",
    padding: "24px",
    maxWidth: "400px",
    width: "100%",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    boxShadow: "0 20px 40px rgba(0, 0, 0, 0.5)",
  },
  modalMobile: {
    padding: "20px",
    borderRadius: "16px",
    maxWidth: "100%",
  },
  modalTitle: {
    fontSize: "18px",
    fontWeight: "600",
    marginBottom: "12px",
    color: "#ffffff",
  },
  modalTitleMobile: {
    fontSize: "16px",
    marginBottom: "10px",
  },
  modalBody: {
    fontSize: "14px",
    color: "#a0aec0",
    lineHeight: "1.5",
    marginBottom: "20px",
  },
  modalBodyMobile: {
    fontSize: "15px",
    marginBottom: "18px",
  },
  modalButtons: {
    display: "flex",
    gap: "12px",
    justifyContent: "flex-end",
  },
  modalButtonsMobile: {
    flexDirection: "column-reverse",
    gap: "10px",
  },
  modalButton: {
    padding: "8px 16px",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s",
    border: "none",
  },
  modalButtonMobile: {
    padding: "12px 16px",
    fontSize: "16px",
    minHeight: "48px",
    borderRadius: "8px",
  },
  modalPrimaryButton: {
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    color: "#0f172a",
    boxShadow: "0 4px 12px rgba(245, 158, 11, 0.3)",
  },
  modalSecondaryButton: {
    backgroundColor: "transparent",
    color: "#a0aec0",
    border: "1px solid rgba(255, 255, 255, 0.2)",
  },
  titleInput: {
    backgroundColor: "#151b26",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    borderRadius: "6px",
    color: "#ffffff",
    fontSize: "16px",
    padding: "8px 12px",
    outline: "none",
    width: "200px",
  },
  titleInputMobile: {
    fontSize: "16px",
    padding: "10px 12px",
    width: "100%",
    maxWidth: "200px",
  },
  emptyStateSidebar: {
    textAlign: "center",
    color: "#6b7280",
    fontSize: "14px",
    padding: "20px",
    lineHeight: "1.5",
  },
  emptyStateSidebarMobile: {
    fontSize: "15px",
    padding: "24px 16px",
  },
  settingsPanel: {
    position: "fixed",
    top: 0,
    right: 0,
    width: "400px",
    height: "100vh",
    backgroundColor: "#0a0f14",
    borderLeft: "1px solid rgba(255, 255, 255, 0.1)",
    zIndex: 1000,
    overflowY: "auto",
    transform: "translateX(100%)",
    transition: "transform 0.3s ease",
  },
  settingsPanelMobile: {
    width: "100vw",
    borderLeft: "none",
  },
  settingsPanelOpen: {
    transform: "translateX(0)",
  },
  settingsHeader: {
    padding: "20px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
    background:
      "linear-gradient(135deg, rgba(245, 158, 11, 0.1) 0%, rgba(251, 191, 36, 0.05) 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  settingsHeaderMobile: {
    padding: "16px",
  },
  settingsTitle: {
    fontSize: "18px",
    fontWeight: "600",
    margin: 0,
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  settingsTitleMobile: {
    fontSize: "16px",
  },
  closeButton: {
    padding: "6px",
    backgroundColor: "transparent",
    border: "none",
    color: "#a0aec0",
    cursor: "pointer",
    borderRadius: "6px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s",
  },
  closeButtonMobile: {
    padding: "8px",
    minWidth: "44px",
    minHeight: "44px",
  },
  settingsContent: {
    padding: "20px",
  },
  settingsContentMobile: {
    padding: "16px",
  },
  settingsSection: {
    marginBottom: "24px",
  },
  settingsSectionMobile: {
    marginBottom: "20px",
  },
  sectionTitle: {
    fontSize: "16px",
    fontWeight: "600",
    marginBottom: "12px",
    color: "#ffffff",
  },
  sectionTitleMobile: {
    fontSize: "15px",
    marginBottom: "10px",
  },
  settingsItem: {
    marginBottom: "16px",
  },
  settingsItemMobile: {
    marginBottom: "14px",
  },
  settingsLabel: {
    fontSize: "14px",
    color: "#a0aec0",
    marginBottom: "6px",
  },
  settingsLabelMobile: {
    fontSize: "15px",
    marginBottom: "8px",
  },
  settingsValue: {
    fontSize: "14px",
    color: "#ffffff",
    fontWeight: "500",
  },
  settingsValueMobile: {
    fontSize: "15px",
  },
  usageBar: {
    marginBottom: "8px",
  },
  cardItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px",
    backgroundColor: "#151b26",
    borderRadius: "8px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  cardItemMobile: {
    padding: "14px",
    borderRadius: "10px",
  },
  buyButton: {
    padding: "6px 12px",
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    border: "none",
    borderRadius: "6px",
    color: "#0f172a",
    fontSize: "12px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s",
    boxShadow: "0 2px 6px rgba(245, 158, 11, 0.3)",
  },
  buyButtonMobile: {
    padding: "10px 16px",
    fontSize: "14px",
    minWidth: "60px",
    minHeight: "40px",
    borderRadius: "8px",
  },
  transactionItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 0",
    borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
  },
  transactionItemMobile: {
    padding: "12px 0",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "4px",
  },
  // Wallet and Settings Panel Styles
  walletCard: {
    padding: "16px",
    backgroundColor: "#151b26",
    borderRadius: "12px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    marginBottom: "16px",
    background:
      "linear-gradient(135deg, rgba(245, 158, 11, 0.05) 0%, rgba(251, 191, 36, 0.02) 100%)",
  },
  walletCardMobile: {
    padding: "14px",
    borderRadius: "10px",
    marginBottom: "14px",
  },
  walletBalance: {
    fontSize: "24px",
    fontWeight: "700",
    color: "#f59e0b",
    marginBottom: "12px",
    textShadow: "0 0 20px rgba(245, 158, 11, 0.3)",
  },
  walletBalanceMobile: {
    fontSize: "22px",
    marginBottom: "10px",
  },
  topUpButton: {
    width: "100%",
    padding: "10px 16px",
    background: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
    border: "none",
    borderRadius: "8px",
    color: "#0f172a",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    transition: "all 0.2s",
    boxShadow: "0 4px 12px rgba(245, 158, 11, 0.3)",
  },
  topUpButtonMobile: {
    padding: "12px 16px",
    fontSize: "16px",
    minHeight: "48px",
    borderRadius: "10px",
  },
  cardInfo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  cardInfoMobile: {
    gap: "10px",
  },
  toggleSwitch: {
    width: "44px",
    height: "24px",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "12px",
    position: "relative",
    cursor: "pointer",
    transition: "all 0.3s ease",
    border: "1px solid rgba(255, 255, 255, 0.2)",
  },
  toggleSwitchMobile: {
    width: "48px",
    height: "28px",
    borderRadius: "14px",
  },
  toggleActive: {
    backgroundColor: "#f59e0b",
    borderColor: "#f59e0b",
    boxShadow: "0 0 20px rgba(245, 158, 11, 0.4)",
  },
  toggleSlider: {
    width: "18px",
    height: "18px",
    backgroundColor: "#ffffff",
    borderRadius: "50%",
    position: "absolute",
    top: "2px",
    left: "2px",
    transition: "all 0.3s ease",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.2)",
  },
  toggleSliderMobile: {
    width: "22px",
    height: "22px",
    top: "2px",
    left: "2px",
  },
};
